### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Terminus\Models\Site::info()

### ISSUE THREAD

**Issue by mustela** [uberhacker/tss#1]
Using `terminus 0.13.2` I'm getting: 

```
PHP Fatal error:  Uncaught Error: Call to undefined method Terminus\Models\Site::info() in /Users/mustela/terminus/plugins/tss-master/Commands/SitesStatusCommand.php:234
Stack trace:
#0 /Users/mustela/terminus/plugins/tss-master/Commands/SitesStatusCommand.php(179): Terminus\Commands\SitesStatusCommand->getStatus(Array, Array)
#1 [internal function]: Terminus\Commands\SitesStatusCommand->status(Array, Array)
#2 phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/CommandFactory.php(131): call_user_func(Array, Array, Array)
#3 [internal function]: Terminus\Dispatcher\CommandFactory::Terminus\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php(118): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/terminus/php/Terminus/Runner.php(309): Terminus\Dispatcher\Subcommand->invoke(Array, Array)
#6 phar:///usr/local/bin/terminus/php/Terminus/Runner.php(212): Terminus\Runner->runCommand()
#7 phar:///usr/local/bin/terminus/php/boot-cl.php(23): Terminus\Runner- in /Users/mustela/terminus/plugins/tss-master/Commands/SitesStatusCommand.php on line 234

Fatal error: Uncaught Error: Call to undefined method Terminus\Models\Site::info() in /Users/mustela/terminus/plugins/tss-master/Commands/SitesStatusCommand.php:234
Stack trace:
#0 /Users/mustela/terminus/plugins/tss-master/Commands/SitesStatusCommand.php(179): Terminus\Commands\SitesStatusCommand->getStatus(Array, Array)
#1 [internal function]: Terminus\Commands\SitesStatusCommand->status(Array, Array)
#2 phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/CommandFactory.php(131): call_user_func(Array, Array, Array)
#3 [internal function]: Terminus\Dispatcher\CommandFactory::Terminus\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php(118): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/terminus/php/Terminus/Runner.php(309): Terminus\Dispatcher\Subcommand->invoke(Array, Array)
#6 phar:///usr/local/bin/terminus/php/Terminus/Runner.php(212): Terminus\Runner->runCommand()
#7 phar:///usr/local/bin/terminus/php/boot-cl.php(23): Terminus\Runner- in /Users/mustela/terminus/plugins/tss-master/Commands/SitesStatusCommand.php on line 234
```

**Comment by uberhacker** [comment]
@mustela: Thank you for the feedback.  I will provide a fix soon.

**Comment by uberhacker** [comment]
@mustela: Please pull the latest changes.  This issue has been fixed.

**Comment by mustela** [comment]
@uberhacker nice thanks!
